//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskClientPC.ImageTaskyServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ImageTaskyServiceReference.I_ImageService")]
    public interface I_ImageService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_ImageService/GetImage", ReplyAction="http://tempuri.org/I_ImageService/GetImageResponse")]
        byte[] GetImage(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_ImageService/GetImage", ReplyAction="http://tempuri.org/I_ImageService/GetImageResponse")]
        System.Threading.Tasks.Task<byte[]> GetImageAsync(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_ImageService/SaveImage", ReplyAction="http://tempuri.org/I_ImageService/SaveImageResponse")]
        string SaveImage(byte[] imgArray, string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_ImageService/SaveImage", ReplyAction="http://tempuri.org/I_ImageService/SaveImageResponse")]
        System.Threading.Tasks.Task<string> SaveImageAsync(byte[] imgArray, string fileName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface I_ImageServiceChannel : TaskClientPC.ImageTaskyServiceReference.I_ImageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class I_ImageServiceClient : System.ServiceModel.ClientBase<TaskClientPC.ImageTaskyServiceReference.I_ImageService>, TaskClientPC.ImageTaskyServiceReference.I_ImageService {
        
        public I_ImageServiceClient() {
        }
        
        public I_ImageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public I_ImageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public I_ImageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public I_ImageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] GetImage(string fileName) {
            return base.Channel.GetImage(fileName);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetImageAsync(string fileName) {
            return base.Channel.GetImageAsync(fileName);
        }
        
        public string SaveImage(byte[] imgArray, string fileName) {
            return base.Channel.SaveImage(imgArray, fileName);
        }
        
        public System.Threading.Tasks.Task<string> SaveImageAsync(byte[] imgArray, string fileName) {
            return base.Channel.SaveImageAsync(imgArray, fileName);
        }
    }
}
