//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserServer
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UserServer.Shift))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UserServer.Assignment))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UserServer.Category))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UserServer.UserInShift))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UserServer.User))]
    public partial class BaseEntity : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private int IDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                if ((this.IDField.Equals(value) != true))
                {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Shift", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Shift : UserServer.BaseEntity
    {
        
        private System.DateTime endField;
        
        private string shiftNameField;
        
        private System.DateTime startField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime end
        {
            get
            {
                return this.endField;
            }
            set
            {
                if ((this.endField.Equals(value) != true))
                {
                    this.endField = value;
                    this.RaisePropertyChanged("end");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string shiftName
        {
            get
            {
                return this.shiftNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.shiftNameField, value) != true))
                {
                    this.shiftNameField = value;
                    this.RaisePropertyChanged("shiftName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime start
        {
            get
            {
                return this.startField;
            }
            set
            {
                if ((this.startField.Equals(value) != true))
                {
                    this.startField = value;
                    this.RaisePropertyChanged("start");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Assignment", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Assignment : UserServer.BaseEntity
    {
        
        private UserServer.Category _categoryField;
        
        private System.DateTime dateOfAssigmentField;
        
        private string descriptionField;
        
        private UserServer.User doneByUserField;
        
        private UserServer.Shift forShiftField;
        
        private UserServer.User forUserField;
        
        private string imageField;
        
        private string subjectField;
        
        private string summeryField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserServer.Category _category
        {
            get
            {
                return this._categoryField;
            }
            set
            {
                if ((object.ReferenceEquals(this._categoryField, value) != true))
                {
                    this._categoryField = value;
                    this.RaisePropertyChanged("_category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dateOfAssigment
        {
            get
            {
                return this.dateOfAssigmentField;
            }
            set
            {
                if ((this.dateOfAssigmentField.Equals(value) != true))
                {
                    this.dateOfAssigmentField = value;
                    this.RaisePropertyChanged("dateOfAssigment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                if ((object.ReferenceEquals(this.descriptionField, value) != true))
                {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserServer.User doneByUser
        {
            get
            {
                return this.doneByUserField;
            }
            set
            {
                if ((object.ReferenceEquals(this.doneByUserField, value) != true))
                {
                    this.doneByUserField = value;
                    this.RaisePropertyChanged("doneByUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserServer.Shift forShift
        {
            get
            {
                return this.forShiftField;
            }
            set
            {
                if ((object.ReferenceEquals(this.forShiftField, value) != true))
                {
                    this.forShiftField = value;
                    this.RaisePropertyChanged("forShift");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserServer.User forUser
        {
            get
            {
                return this.forUserField;
            }
            set
            {
                if ((object.ReferenceEquals(this.forUserField, value) != true))
                {
                    this.forUserField = value;
                    this.RaisePropertyChanged("forUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string image
        {
            get
            {
                return this.imageField;
            }
            set
            {
                if ((object.ReferenceEquals(this.imageField, value) != true))
                {
                    this.imageField = value;
                    this.RaisePropertyChanged("image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string subject
        {
            get
            {
                return this.subjectField;
            }
            set
            {
                if ((object.ReferenceEquals(this.subjectField, value) != true))
                {
                    this.subjectField = value;
                    this.RaisePropertyChanged("subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string summery
        {
            get
            {
                return this.summeryField;
            }
            set
            {
                if ((object.ReferenceEquals(this.summeryField, value) != true))
                {
                    this.summeryField = value;
                    this.RaisePropertyChanged("summery");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Category : UserServer.BaseEntity
    {
        
        private string nameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.nameField, value) != true))
                {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInShift", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class UserInShift : UserServer.BaseEntity
    {
        
        private UserServer.Shift _shiftField;
        
        private UserServer.User _userField;
        
        private bool isClockedInField;
        
        private bool isClockedOutField;
        
        private System.DateTime userClockInField;
        
        private System.Nullable<System.DateTime> userClockOutField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserServer.Shift _shift
        {
            get
            {
                return this._shiftField;
            }
            set
            {
                if ((object.ReferenceEquals(this._shiftField, value) != true))
                {
                    this._shiftField = value;
                    this.RaisePropertyChanged("_shift");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserServer.User _user
        {
            get
            {
                return this._userField;
            }
            set
            {
                if ((object.ReferenceEquals(this._userField, value) != true))
                {
                    this._userField = value;
                    this.RaisePropertyChanged("_user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isClockedIn
        {
            get
            {
                return this.isClockedInField;
            }
            set
            {
                if ((this.isClockedInField.Equals(value) != true))
                {
                    this.isClockedInField = value;
                    this.RaisePropertyChanged("isClockedIn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isClockedOut
        {
            get
            {
                return this.isClockedOutField;
            }
            set
            {
                if ((this.isClockedOutField.Equals(value) != true))
                {
                    this.isClockedOutField = value;
                    this.RaisePropertyChanged("isClockedOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime userClockIn
        {
            get
            {
                return this.userClockInField;
            }
            set
            {
                if ((this.userClockInField.Equals(value) != true))
                {
                    this.userClockInField = value;
                    this.RaisePropertyChanged("userClockIn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> userClockOut
        {
            get
            {
                return this.userClockOutField;
            }
            set
            {
                if ((this.userClockOutField.Equals(value) != true))
                {
                    this.userClockOutField = value;
                    this.RaisePropertyChanged("userClockOut");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class User : UserServer.BaseEntity
    {
        
        private System.DateTime birthdayField;
        
        private string emailField;
        
        private string firstnameField;
        
        private string lastnameField;
        
        private string passwordField;
        
        private UserServer.UserType userTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime birthday
        {
            get
            {
                return this.birthdayField;
            }
            set
            {
                if ((this.birthdayField.Equals(value) != true))
                {
                    this.birthdayField = value;
                    this.RaisePropertyChanged("birthday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                if ((object.ReferenceEquals(this.emailField, value) != true))
                {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstname
        {
            get
            {
                return this.firstnameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.firstnameField, value) != true))
                {
                    this.firstnameField = value;
                    this.RaisePropertyChanged("firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastname
        {
            get
            {
                return this.lastnameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.lastnameField, value) != true))
                {
                    this.lastnameField = value;
                    this.RaisePropertyChanged("lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                if ((object.ReferenceEquals(this.passwordField, value) != true))
                {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserServer.UserType userType
        {
            get
            {
                return this.userTypeField;
            }
            set
            {
                if ((this.userTypeField.Equals(value) != true))
                {
                    this.userTypeField = value;
                    this.RaisePropertyChanged("userType");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserType", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public enum UserType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Admin = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ShiftManager = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Worker = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="UserList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="User")]
    public class UserList : System.Collections.Generic.List<UserServer.User>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ShiftList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="Shift")]
    public class ShiftList : System.Collections.Generic.List<UserServer.Shift>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="AssignmentList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="Assignment")]
    public class AssignmentList : System.Collections.Generic.List<UserServer.Assignment>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="UserInShiftList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="UserInShift")]
    public class UserInShiftList : System.Collections.Generic.List<UserServer.UserInShift>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="CategoryList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="Category")]
    public class CategoryList : System.Collections.Generic.List<UserServer.Category>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserServer.IUserService")]
    public interface IUserService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UserLogin", ReplyAction="http://tempuri.org/IUserService/UserLoginResponse")]
        System.Threading.Tasks.Task<UserServer.User> UserLoginAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/NewUser", ReplyAction="http://tempuri.org/IUserService/NewUserResponse")]
        System.Threading.Tasks.Task<UserServer.User> NewUserAsync(UserServer.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateUser", ReplyAction="http://tempuri.org/IUserService/UpdateUserResponse")]
        System.Threading.Tasks.Task<bool> UpdateUserAsync(UserServer.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DeleteUser", ReplyAction="http://tempuri.org/IUserService/DeleteUserResponse")]
        System.Threading.Tasks.Task<bool> DeleteUserAsync(UserServer.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/IsEmailFree", ReplyAction="http://tempuri.org/IUserService/IsEmailFreeResponse")]
        System.Threading.Tasks.Task<bool> IsEmailFreeAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserByEmail", ReplyAction="http://tempuri.org/IUserService/GetUserByEmailResponse")]
        System.Threading.Tasks.Task<UserServer.User> GetUserByEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUsersbyType", ReplyAction="http://tempuri.org/IUserService/GetUsersbyTypeResponse")]
        System.Threading.Tasks.Task<UserServer.UserList> GetUsersbyTypeAsync(UserServer.UserType type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUsers", ReplyAction="http://tempuri.org/IUserService/GetUsersResponse")]
        System.Threading.Tasks.Task<UserServer.UserList> GetUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetShifts", ReplyAction="http://tempuri.org/IUserService/GetShiftsResponse")]
        System.Threading.Tasks.Task<UserServer.ShiftList> GetShiftsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetPastShifts", ReplyAction="http://tempuri.org/IUserService/GetPastShiftsResponse")]
        System.Threading.Tasks.Task<UserServer.ShiftList> GetPastShiftsAsync(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetFutureShifts", ReplyAction="http://tempuri.org/IUserService/GetFutureShiftsResponse")]
        System.Threading.Tasks.Task<UserServer.ShiftList> GetFutureShiftsAsync(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetShift", ReplyAction="http://tempuri.org/IUserService/GetShiftResponse")]
        System.Threading.Tasks.Task<UserServer.Shift> GetShiftAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/NewShift", ReplyAction="http://tempuri.org/IUserService/NewShiftResponse")]
        System.Threading.Tasks.Task<UserServer.Shift> NewShiftAsync(UserServer.Shift shift);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateShift", ReplyAction="http://tempuri.org/IUserService/UpdateShiftResponse")]
        System.Threading.Tasks.Task UpdateShiftAsync(UserServer.Shift shift);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DeleteShift", ReplyAction="http://tempuri.org/IUserService/DeleteShiftResponse")]
        System.Threading.Tasks.Task<bool> DeleteShiftAsync(UserServer.Shift shift);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAssignments", ReplyAction="http://tempuri.org/IUserService/GetAssignmentsResponse")]
        System.Threading.Tasks.Task<UserServer.AssignmentList> GetAssignmentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAssignmentById", ReplyAction="http://tempuri.org/IUserService/GetAssignmentByIdResponse")]
        System.Threading.Tasks.Task<UserServer.Assignment> GetAssignmentByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAssignmentsBySubject", ReplyAction="http://tempuri.org/IUserService/GetAssignmentsBySubjectResponse")]
        System.Threading.Tasks.Task<UserServer.Assignment> GetAssignmentsBySubjectAsync(string Subject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAssignmentsByCategory", ReplyAction="http://tempuri.org/IUserService/GetAssignmentsByCategoryResponse")]
        System.Threading.Tasks.Task<UserServer.AssignmentList> GetAssignmentsByCategoryAsync(string Category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAssignmentByShift", ReplyAction="http://tempuri.org/IUserService/GetAssignmentByShiftResponse")]
        System.Threading.Tasks.Task<UserServer.AssignmentList> GetAssignmentByShiftAsync(UserServer.Shift shift);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/NewAssignment", ReplyAction="http://tempuri.org/IUserService/NewAssignmentResponse")]
        System.Threading.Tasks.Task<UserServer.Assignment> NewAssignmentAsync(UserServer.Assignment assignment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateAssignment", ReplyAction="http://tempuri.org/IUserService/UpdateAssignmentResponse")]
        System.Threading.Tasks.Task<bool> UpdateAssignmentAsync(UserServer.Assignment assignment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DeleteAssignment", ReplyAction="http://tempuri.org/IUserService/DeleteAssignmentResponse")]
        System.Threading.Tasks.Task<bool> DeleteAssignmentAsync(UserServer.Assignment assignment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAllUsersInShift", ReplyAction="http://tempuri.org/IUserService/GetAllUsersInShiftResponse")]
        System.Threading.Tasks.Task<UserServer.UserInShiftList> GetAllUsersInShiftAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUsersInShift", ReplyAction="http://tempuri.org/IUserService/GetUsersInShiftResponse")]
        System.Threading.Tasks.Task<UserServer.UserInShiftList> GetUsersInShiftAsync(UserServer.Shift shift);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetByUser", ReplyAction="http://tempuri.org/IUserService/GetByUserResponse")]
        System.Threading.Tasks.Task<UserServer.UserInShift> GetByUserAsync(UserServer.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/NewUserInShift", ReplyAction="http://tempuri.org/IUserService/NewUserInShiftResponse")]
        System.Threading.Tasks.Task<UserServer.UserInShift> NewUserInShiftAsync(UserServer.UserInShift user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateUserInShift", ReplyAction="http://tempuri.org/IUserService/UpdateUserInShiftResponse")]
        System.Threading.Tasks.Task<bool> UpdateUserInShiftAsync(UserServer.UserInShift user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/FullUpdateUserInShift", ReplyAction="http://tempuri.org/IUserService/FullUpdateUserInShiftResponse")]
        System.Threading.Tasks.Task<bool> FullUpdateUserInShiftAsync(UserServer.UserInShift user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DeleteUserInShift", ReplyAction="http://tempuri.org/IUserService/DeleteUserInShiftResponse")]
        System.Threading.Tasks.Task<bool> DeleteUserInShiftAsync(UserServer.UserInShift user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetCategories", ReplyAction="http://tempuri.org/IUserService/GetCategoriesResponse")]
        System.Threading.Tasks.Task<UserServer.CategoryList> GetCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetByName", ReplyAction="http://tempuri.org/IUserService/GetByNameResponse")]
        System.Threading.Tasks.Task<UserServer.Category> GetByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/NewCategory", ReplyAction="http://tempuri.org/IUserService/NewCategoryResponse")]
        System.Threading.Tasks.Task<UserServer.Category> NewCategoryAsync(UserServer.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateCategory", ReplyAction="http://tempuri.org/IUserService/UpdateCategoryResponse")]
        System.Threading.Tasks.Task<bool> UpdateCategoryAsync(UserServer.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DeleteCategory", ReplyAction="http://tempuri.org/IUserService/DeleteCategoryResponse")]
        System.Threading.Tasks.Task<bool> DeleteCategoryAsync(UserServer.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/SendEmailAsync", ReplyAction="http://tempuri.org/IUserService/SendEmailAsyncResponse")]
        System.Threading.Tasks.Task SendEmailAsyncAsync(string fromEmail, string toEmail, string subject, string body);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/SendEmailUsingTemplateAsync", ReplyAction="http://tempuri.org/IUserService/SendEmailUsingTemplateAsyncResponse")]
        System.Threading.Tasks.Task SendEmailUsingTemplateAsyncAsync(string toEmail, string Text);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IUserServiceChannel : UserServer.IUserService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<UserServer.IUserService>, UserServer.IUserService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public UserServiceClient() : 
                base(UserServiceClient.GetDefaultBinding(), UserServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IUserService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(UserServiceClient.GetBindingForEndpoint(endpointConfiguration), UserServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(UserServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(UserServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<UserServer.User> UserLoginAsync(string email, string password)
        {
            return base.Channel.UserLoginAsync(email, password);
        }
        
        public System.Threading.Tasks.Task<UserServer.User> NewUserAsync(UserServer.User user)
        {
            return base.Channel.NewUserAsync(user);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateUserAsync(UserServer.User user)
        {
            return base.Channel.UpdateUserAsync(user);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteUserAsync(UserServer.User user)
        {
            return base.Channel.DeleteUserAsync(user);
        }
        
        public System.Threading.Tasks.Task<bool> IsEmailFreeAsync(string email)
        {
            return base.Channel.IsEmailFreeAsync(email);
        }
        
        public System.Threading.Tasks.Task<UserServer.User> GetUserByEmailAsync(string email)
        {
            return base.Channel.GetUserByEmailAsync(email);
        }
        
        public System.Threading.Tasks.Task<UserServer.UserList> GetUsersbyTypeAsync(UserServer.UserType type)
        {
            return base.Channel.GetUsersbyTypeAsync(type);
        }
        
        public System.Threading.Tasks.Task<UserServer.UserList> GetUsersAsync()
        {
            return base.Channel.GetUsersAsync();
        }
        
        public System.Threading.Tasks.Task<UserServer.ShiftList> GetShiftsAsync()
        {
            return base.Channel.GetShiftsAsync();
        }
        
        public System.Threading.Tasks.Task<UserServer.ShiftList> GetPastShiftsAsync(System.DateTime date)
        {
            return base.Channel.GetPastShiftsAsync(date);
        }
        
        public System.Threading.Tasks.Task<UserServer.ShiftList> GetFutureShiftsAsync(System.DateTime date)
        {
            return base.Channel.GetFutureShiftsAsync(date);
        }
        
        public System.Threading.Tasks.Task<UserServer.Shift> GetShiftAsync(string name)
        {
            return base.Channel.GetShiftAsync(name);
        }
        
        public System.Threading.Tasks.Task<UserServer.Shift> NewShiftAsync(UserServer.Shift shift)
        {
            return base.Channel.NewShiftAsync(shift);
        }
        
        public System.Threading.Tasks.Task UpdateShiftAsync(UserServer.Shift shift)
        {
            return base.Channel.UpdateShiftAsync(shift);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteShiftAsync(UserServer.Shift shift)
        {
            return base.Channel.DeleteShiftAsync(shift);
        }
        
        public System.Threading.Tasks.Task<UserServer.AssignmentList> GetAssignmentsAsync()
        {
            return base.Channel.GetAssignmentsAsync();
        }
        
        public System.Threading.Tasks.Task<UserServer.Assignment> GetAssignmentByIdAsync(int id)
        {
            return base.Channel.GetAssignmentByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<UserServer.Assignment> GetAssignmentsBySubjectAsync(string Subject)
        {
            return base.Channel.GetAssignmentsBySubjectAsync(Subject);
        }
        
        public System.Threading.Tasks.Task<UserServer.AssignmentList> GetAssignmentsByCategoryAsync(string Category)
        {
            return base.Channel.GetAssignmentsByCategoryAsync(Category);
        }
        
        public System.Threading.Tasks.Task<UserServer.AssignmentList> GetAssignmentByShiftAsync(UserServer.Shift shift)
        {
            return base.Channel.GetAssignmentByShiftAsync(shift);
        }
        
        public System.Threading.Tasks.Task<UserServer.Assignment> NewAssignmentAsync(UserServer.Assignment assignment)
        {
            return base.Channel.NewAssignmentAsync(assignment);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAssignmentAsync(UserServer.Assignment assignment)
        {
            return base.Channel.UpdateAssignmentAsync(assignment);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAssignmentAsync(UserServer.Assignment assignment)
        {
            return base.Channel.DeleteAssignmentAsync(assignment);
        }
        
        public System.Threading.Tasks.Task<UserServer.UserInShiftList> GetAllUsersInShiftAsync()
        {
            return base.Channel.GetAllUsersInShiftAsync();
        }
        
        public System.Threading.Tasks.Task<UserServer.UserInShiftList> GetUsersInShiftAsync(UserServer.Shift shift)
        {
            return base.Channel.GetUsersInShiftAsync(shift);
        }
        
        public System.Threading.Tasks.Task<UserServer.UserInShift> GetByUserAsync(UserServer.User user)
        {
            return base.Channel.GetByUserAsync(user);
        }
        
        public System.Threading.Tasks.Task<UserServer.UserInShift> NewUserInShiftAsync(UserServer.UserInShift user)
        {
            return base.Channel.NewUserInShiftAsync(user);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateUserInShiftAsync(UserServer.UserInShift user)
        {
            return base.Channel.UpdateUserInShiftAsync(user);
        }
        
        public System.Threading.Tasks.Task<bool> FullUpdateUserInShiftAsync(UserServer.UserInShift user)
        {
            return base.Channel.FullUpdateUserInShiftAsync(user);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteUserInShiftAsync(UserServer.UserInShift user)
        {
            return base.Channel.DeleteUserInShiftAsync(user);
        }
        
        public System.Threading.Tasks.Task<UserServer.CategoryList> GetCategoriesAsync()
        {
            return base.Channel.GetCategoriesAsync();
        }
        
        public System.Threading.Tasks.Task<UserServer.Category> GetByNameAsync(string name)
        {
            return base.Channel.GetByNameAsync(name);
        }
        
        public System.Threading.Tasks.Task<UserServer.Category> NewCategoryAsync(UserServer.Category category)
        {
            return base.Channel.NewCategoryAsync(category);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateCategoryAsync(UserServer.Category category)
        {
            return base.Channel.UpdateCategoryAsync(category);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteCategoryAsync(UserServer.Category category)
        {
            return base.Channel.DeleteCategoryAsync(category);
        }
        
        public System.Threading.Tasks.Task SendEmailAsyncAsync(string fromEmail, string toEmail, string subject, string body)
        {
            return base.Channel.SendEmailAsyncAsync(fromEmail, toEmail, subject, body);
        }
        
        public System.Threading.Tasks.Task SendEmailUsingTemplateAsyncAsync(string toEmail, string Text)
        {
            return base.Channel.SendEmailUsingTemplateAsyncAsync(toEmail, Text);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IUserService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IUserService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WcfService/UserService/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return UserServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IUserService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return UserServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IUserService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IUserService,
        }
    }
}
