//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserServer
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UserServer.Shift))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UserServer.Assignment))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UserServer.Category))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UserServer.UserInShift))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UserServer.User))]
    public partial class BaseEntity : object
    {
        
        private int IDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Shift", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Shift : UserServer.BaseEntity
    {
        
        private System.DateTime endField;
        
        private string shiftNameField;
        
        private System.DateTime startField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime end
        {
            get
            {
                return this.endField;
            }
            set
            {
                this.endField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string shiftName
        {
            get
            {
                return this.shiftNameField;
            }
            set
            {
                this.shiftNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime start
        {
            get
            {
                return this.startField;
            }
            set
            {
                this.startField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Assignment", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Assignment : UserServer.BaseEntity
    {
        
        private UserServer.Category _categoryField;
        
        private System.DateTime dateOfAssigmentField;
        
        private string descriptionField;
        
        private UserServer.User doneByUserField;
        
        private UserServer.Shift forShiftField;
        
        private UserServer.User forUserField;
        
        private string imageField;
        
        private string subjectField;
        
        private string summeryField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserServer.Category _category
        {
            get
            {
                return this._categoryField;
            }
            set
            {
                this._categoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dateOfAssigment
        {
            get
            {
                return this.dateOfAssigmentField;
            }
            set
            {
                this.dateOfAssigmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserServer.User doneByUser
        {
            get
            {
                return this.doneByUserField;
            }
            set
            {
                this.doneByUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserServer.Shift forShift
        {
            get
            {
                return this.forShiftField;
            }
            set
            {
                this.forShiftField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserServer.User forUser
        {
            get
            {
                return this.forUserField;
            }
            set
            {
                this.forUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string image
        {
            get
            {
                return this.imageField;
            }
            set
            {
                this.imageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string subject
        {
            get
            {
                return this.subjectField;
            }
            set
            {
                this.subjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string summery
        {
            get
            {
                return this.summeryField;
            }
            set
            {
                this.summeryField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Category : UserServer.BaseEntity
    {
        
        private string nameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInShift", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class UserInShift : UserServer.BaseEntity
    {
        
        private UserServer.Shift _shiftField;
        
        private UserServer.User _userField;
        
        private bool isClockedInField;
        
        private bool isClockedOutField;
        
        private System.DateTime userClockInField;
        
        private System.DateTime userClockOutField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserServer.Shift _shift
        {
            get
            {
                return this._shiftField;
            }
            set
            {
                this._shiftField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserServer.User _user
        {
            get
            {
                return this._userField;
            }
            set
            {
                this._userField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isClockedIn
        {
            get
            {
                return this.isClockedInField;
            }
            set
            {
                this.isClockedInField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isClockedOut
        {
            get
            {
                return this.isClockedOutField;
            }
            set
            {
                this.isClockedOutField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime userClockIn
        {
            get
            {
                return this.userClockInField;
            }
            set
            {
                this.userClockInField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime userClockOut
        {
            get
            {
                return this.userClockOutField;
            }
            set
            {
                this.userClockOutField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class User : UserServer.BaseEntity
    {
        
        private System.DateTime birthdayField;
        
        private string emailField;
        
        private string firstnameField;
        
        private string lastnameField;
        
        private string passwordField;
        
        private UserServer.UserType userTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime birthday
        {
            get
            {
                return this.birthdayField;
            }
            set
            {
                this.birthdayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstname
        {
            get
            {
                return this.firstnameField;
            }
            set
            {
                this.firstnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastname
        {
            get
            {
                return this.lastnameField;
            }
            set
            {
                this.lastnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserServer.UserType userType
        {
            get
            {
                return this.userTypeField;
            }
            set
            {
                this.userTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserType", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public enum UserType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Admin = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ShiftManager = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Worker = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="UserList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="User")]
    public class UserList : System.Collections.Generic.List<UserServer.User>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ShiftList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="Shift")]
    public class ShiftList : System.Collections.Generic.List<UserServer.Shift>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="AssignmentList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="Assignment")]
    public class AssignmentList : System.Collections.Generic.List<UserServer.Assignment>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="UserInShiftList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="UserInShift")]
    public class UserInShiftList : System.Collections.Generic.List<UserServer.UserInShift>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="CategoryList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="Category")]
    public class CategoryList : System.Collections.Generic.List<UserServer.Category>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserServer.IUserService")]
    public interface IUserService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UserLogin", ReplyAction="http://tempuri.org/IUserService/UserLoginResponse")]
        UserServer.User UserLogin(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UserLogin", ReplyAction="http://tempuri.org/IUserService/UserLoginResponse")]
        System.Threading.Tasks.Task<UserServer.User> UserLoginAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/NewUser", ReplyAction="http://tempuri.org/IUserService/NewUserResponse")]
        UserServer.User NewUser(UserServer.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/NewUser", ReplyAction="http://tempuri.org/IUserService/NewUserResponse")]
        System.Threading.Tasks.Task<UserServer.User> NewUserAsync(UserServer.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateUser", ReplyAction="http://tempuri.org/IUserService/UpdateUserResponse")]
        bool UpdateUser(UserServer.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateUser", ReplyAction="http://tempuri.org/IUserService/UpdateUserResponse")]
        System.Threading.Tasks.Task<bool> UpdateUserAsync(UserServer.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DeleteUser", ReplyAction="http://tempuri.org/IUserService/DeleteUserResponse")]
        bool DeleteUser(UserServer.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DeleteUser", ReplyAction="http://tempuri.org/IUserService/DeleteUserResponse")]
        System.Threading.Tasks.Task<bool> DeleteUserAsync(UserServer.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/IsEmailFree", ReplyAction="http://tempuri.org/IUserService/IsEmailFreeResponse")]
        bool IsEmailFree(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/IsEmailFree", ReplyAction="http://tempuri.org/IUserService/IsEmailFreeResponse")]
        System.Threading.Tasks.Task<bool> IsEmailFreeAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUsersbyType", ReplyAction="http://tempuri.org/IUserService/GetUsersbyTypeResponse")]
        UserServer.UserList GetUsersbyType(UserServer.UserType type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUsersbyType", ReplyAction="http://tempuri.org/IUserService/GetUsersbyTypeResponse")]
        System.Threading.Tasks.Task<UserServer.UserList> GetUsersbyTypeAsync(UserServer.UserType type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUsers", ReplyAction="http://tempuri.org/IUserService/GetUsersResponse")]
        UserServer.UserList GetUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUsers", ReplyAction="http://tempuri.org/IUserService/GetUsersResponse")]
        System.Threading.Tasks.Task<UserServer.UserList> GetUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetShifts", ReplyAction="http://tempuri.org/IUserService/GetShiftsResponse")]
        UserServer.ShiftList GetShifts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetShifts", ReplyAction="http://tempuri.org/IUserService/GetShiftsResponse")]
        System.Threading.Tasks.Task<UserServer.ShiftList> GetShiftsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetPastShifts", ReplyAction="http://tempuri.org/IUserService/GetPastShiftsResponse")]
        UserServer.ShiftList GetPastShifts(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetPastShifts", ReplyAction="http://tempuri.org/IUserService/GetPastShiftsResponse")]
        System.Threading.Tasks.Task<UserServer.ShiftList> GetPastShiftsAsync(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetFutureShifts", ReplyAction="http://tempuri.org/IUserService/GetFutureShiftsResponse")]
        UserServer.ShiftList GetFutureShifts(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetFutureShifts", ReplyAction="http://tempuri.org/IUserService/GetFutureShiftsResponse")]
        System.Threading.Tasks.Task<UserServer.ShiftList> GetFutureShiftsAsync(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetShift", ReplyAction="http://tempuri.org/IUserService/GetShiftResponse")]
        UserServer.Shift GetShift(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetShift", ReplyAction="http://tempuri.org/IUserService/GetShiftResponse")]
        System.Threading.Tasks.Task<UserServer.Shift> GetShiftAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/NewShift", ReplyAction="http://tempuri.org/IUserService/NewShiftResponse")]
        UserServer.Shift NewShift(UserServer.Shift shift);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/NewShift", ReplyAction="http://tempuri.org/IUserService/NewShiftResponse")]
        System.Threading.Tasks.Task<UserServer.Shift> NewShiftAsync(UserServer.Shift shift);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateShift", ReplyAction="http://tempuri.org/IUserService/UpdateShiftResponse")]
        void UpdateShift(UserServer.Shift shift);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateShift", ReplyAction="http://tempuri.org/IUserService/UpdateShiftResponse")]
        System.Threading.Tasks.Task UpdateShiftAsync(UserServer.Shift shift);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DeleteShift", ReplyAction="http://tempuri.org/IUserService/DeleteShiftResponse")]
        bool DeleteShift(UserServer.Shift shift);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DeleteShift", ReplyAction="http://tempuri.org/IUserService/DeleteShiftResponse")]
        System.Threading.Tasks.Task<bool> DeleteShiftAsync(UserServer.Shift shift);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAssignments", ReplyAction="http://tempuri.org/IUserService/GetAssignmentsResponse")]
        UserServer.AssignmentList GetAssignments();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAssignments", ReplyAction="http://tempuri.org/IUserService/GetAssignmentsResponse")]
        System.Threading.Tasks.Task<UserServer.AssignmentList> GetAssignmentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAssignmentById", ReplyAction="http://tempuri.org/IUserService/GetAssignmentByIdResponse")]
        UserServer.Assignment GetAssignmentById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAssignmentById", ReplyAction="http://tempuri.org/IUserService/GetAssignmentByIdResponse")]
        System.Threading.Tasks.Task<UserServer.Assignment> GetAssignmentByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAssignmentsBySubject", ReplyAction="http://tempuri.org/IUserService/GetAssignmentsBySubjectResponse")]
        UserServer.Assignment GetAssignmentsBySubject(string Subject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAssignmentsBySubject", ReplyAction="http://tempuri.org/IUserService/GetAssignmentsBySubjectResponse")]
        System.Threading.Tasks.Task<UserServer.Assignment> GetAssignmentsBySubjectAsync(string Subject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAssignmentsByCategory", ReplyAction="http://tempuri.org/IUserService/GetAssignmentsByCategoryResponse")]
        UserServer.AssignmentList GetAssignmentsByCategory(string Category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAssignmentsByCategory", ReplyAction="http://tempuri.org/IUserService/GetAssignmentsByCategoryResponse")]
        System.Threading.Tasks.Task<UserServer.AssignmentList> GetAssignmentsByCategoryAsync(string Category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAssignmentByShift", ReplyAction="http://tempuri.org/IUserService/GetAssignmentByShiftResponse")]
        UserServer.AssignmentList GetAssignmentByShift(UserServer.Shift shift);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAssignmentByShift", ReplyAction="http://tempuri.org/IUserService/GetAssignmentByShiftResponse")]
        System.Threading.Tasks.Task<UserServer.AssignmentList> GetAssignmentByShiftAsync(UserServer.Shift shift);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/NewAssignment", ReplyAction="http://tempuri.org/IUserService/NewAssignmentResponse")]
        UserServer.Assignment NewAssignment(UserServer.Assignment assignment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/NewAssignment", ReplyAction="http://tempuri.org/IUserService/NewAssignmentResponse")]
        System.Threading.Tasks.Task<UserServer.Assignment> NewAssignmentAsync(UserServer.Assignment assignment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateAssignment", ReplyAction="http://tempuri.org/IUserService/UpdateAssignmentResponse")]
        void UpdateAssignment(UserServer.Assignment assignment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateAssignment", ReplyAction="http://tempuri.org/IUserService/UpdateAssignmentResponse")]
        System.Threading.Tasks.Task UpdateAssignmentAsync(UserServer.Assignment assignment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DeleteAssignment", ReplyAction="http://tempuri.org/IUserService/DeleteAssignmentResponse")]
        bool DeleteAssignment(UserServer.Assignment assignment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DeleteAssignment", ReplyAction="http://tempuri.org/IUserService/DeleteAssignmentResponse")]
        System.Threading.Tasks.Task<bool> DeleteAssignmentAsync(UserServer.Assignment assignment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUsersInShift", ReplyAction="http://tempuri.org/IUserService/GetUsersInShiftResponse")]
        UserServer.UserInShiftList GetUsersInShift();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUsersInShift", ReplyAction="http://tempuri.org/IUserService/GetUsersInShiftResponse")]
        System.Threading.Tasks.Task<UserServer.UserInShiftList> GetUsersInShiftAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetByUser", ReplyAction="http://tempuri.org/IUserService/GetByUserResponse")]
        UserServer.UserInShift GetByUser(UserServer.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetByUser", ReplyAction="http://tempuri.org/IUserService/GetByUserResponse")]
        System.Threading.Tasks.Task<UserServer.UserInShift> GetByUserAsync(UserServer.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/NewUserInShift", ReplyAction="http://tempuri.org/IUserService/NewUserInShiftResponse")]
        UserServer.UserInShift NewUserInShift(UserServer.UserInShift user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/NewUserInShift", ReplyAction="http://tempuri.org/IUserService/NewUserInShiftResponse")]
        System.Threading.Tasks.Task<UserServer.UserInShift> NewUserInShiftAsync(UserServer.UserInShift user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateUserInShift", ReplyAction="http://tempuri.org/IUserService/UpdateUserInShiftResponse")]
        bool UpdateUserInShift(UserServer.UserInShift user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateUserInShift", ReplyAction="http://tempuri.org/IUserService/UpdateUserInShiftResponse")]
        System.Threading.Tasks.Task<bool> UpdateUserInShiftAsync(UserServer.UserInShift user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DeleteUserInShift", ReplyAction="http://tempuri.org/IUserService/DeleteUserInShiftResponse")]
        bool DeleteUserInShift(UserServer.UserInShift user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DeleteUserInShift", ReplyAction="http://tempuri.org/IUserService/DeleteUserInShiftResponse")]
        System.Threading.Tasks.Task<bool> DeleteUserInShiftAsync(UserServer.UserInShift user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetCategories", ReplyAction="http://tempuri.org/IUserService/GetCategoriesResponse")]
        UserServer.CategoryList GetCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetCategories", ReplyAction="http://tempuri.org/IUserService/GetCategoriesResponse")]
        System.Threading.Tasks.Task<UserServer.CategoryList> GetCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetByName", ReplyAction="http://tempuri.org/IUserService/GetByNameResponse")]
        UserServer.Category GetByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetByName", ReplyAction="http://tempuri.org/IUserService/GetByNameResponse")]
        System.Threading.Tasks.Task<UserServer.Category> GetByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/NewCategory", ReplyAction="http://tempuri.org/IUserService/NewCategoryResponse")]
        UserServer.Category NewCategory(UserServer.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/NewCategory", ReplyAction="http://tempuri.org/IUserService/NewCategoryResponse")]
        System.Threading.Tasks.Task<UserServer.Category> NewCategoryAsync(UserServer.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateCategory", ReplyAction="http://tempuri.org/IUserService/UpdateCategoryResponse")]
        bool UpdateCategory(UserServer.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateCategory", ReplyAction="http://tempuri.org/IUserService/UpdateCategoryResponse")]
        System.Threading.Tasks.Task<bool> UpdateCategoryAsync(UserServer.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DeleteCategory", ReplyAction="http://tempuri.org/IUserService/DeleteCategoryResponse")]
        bool DeleteCategory(UserServer.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DeleteCategory", ReplyAction="http://tempuri.org/IUserService/DeleteCategoryResponse")]
        System.Threading.Tasks.Task<bool> DeleteCategoryAsync(UserServer.Category category);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IUserServiceChannel : UserServer.IUserService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<UserServer.IUserService>, UserServer.IUserService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public UserServiceClient() : 
                base(UserServiceClient.GetDefaultBinding(), UserServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IUserService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(UserServiceClient.GetBindingForEndpoint(endpointConfiguration), UserServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(UserServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(UserServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public UserServer.User UserLogin(string email, string password)
        {
            return base.Channel.UserLogin(email, password);
        }
        
        public System.Threading.Tasks.Task<UserServer.User> UserLoginAsync(string email, string password)
        {
            return base.Channel.UserLoginAsync(email, password);
        }
        
        public UserServer.User NewUser(UserServer.User user)
        {
            return base.Channel.NewUser(user);
        }
        
        public System.Threading.Tasks.Task<UserServer.User> NewUserAsync(UserServer.User user)
        {
            return base.Channel.NewUserAsync(user);
        }
        
        public bool UpdateUser(UserServer.User user)
        {
            return base.Channel.UpdateUser(user);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateUserAsync(UserServer.User user)
        {
            return base.Channel.UpdateUserAsync(user);
        }
        
        public bool DeleteUser(UserServer.User user)
        {
            return base.Channel.DeleteUser(user);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteUserAsync(UserServer.User user)
        {
            return base.Channel.DeleteUserAsync(user);
        }
        
        public bool IsEmailFree(string email)
        {
            return base.Channel.IsEmailFree(email);
        }
        
        public System.Threading.Tasks.Task<bool> IsEmailFreeAsync(string email)
        {
            return base.Channel.IsEmailFreeAsync(email);
        }
        
        public UserServer.UserList GetUsersbyType(UserServer.UserType type)
        {
            return base.Channel.GetUsersbyType(type);
        }
        
        public System.Threading.Tasks.Task<UserServer.UserList> GetUsersbyTypeAsync(UserServer.UserType type)
        {
            return base.Channel.GetUsersbyTypeAsync(type);
        }
        
        public UserServer.UserList GetUsers()
        {
            return base.Channel.GetUsers();
        }
        
        public System.Threading.Tasks.Task<UserServer.UserList> GetUsersAsync()
        {
            return base.Channel.GetUsersAsync();
        }
        
        public UserServer.ShiftList GetShifts()
        {
            return base.Channel.GetShifts();
        }
        
        public System.Threading.Tasks.Task<UserServer.ShiftList> GetShiftsAsync()
        {
            return base.Channel.GetShiftsAsync();
        }
        
        public UserServer.ShiftList GetPastShifts(System.DateTime date)
        {
            return base.Channel.GetPastShifts(date);
        }
        
        public System.Threading.Tasks.Task<UserServer.ShiftList> GetPastShiftsAsync(System.DateTime date)
        {
            return base.Channel.GetPastShiftsAsync(date);
        }
        
        public UserServer.ShiftList GetFutureShifts(System.DateTime date)
        {
            return base.Channel.GetFutureShifts(date);
        }
        
        public System.Threading.Tasks.Task<UserServer.ShiftList> GetFutureShiftsAsync(System.DateTime date)
        {
            return base.Channel.GetFutureShiftsAsync(date);
        }
        
        public UserServer.Shift GetShift(string name)
        {
            return base.Channel.GetShift(name);
        }
        
        public System.Threading.Tasks.Task<UserServer.Shift> GetShiftAsync(string name)
        {
            return base.Channel.GetShiftAsync(name);
        }
        
        public UserServer.Shift NewShift(UserServer.Shift shift)
        {
            return base.Channel.NewShift(shift);
        }
        
        public System.Threading.Tasks.Task<UserServer.Shift> NewShiftAsync(UserServer.Shift shift)
        {
            return base.Channel.NewShiftAsync(shift);
        }
        
        public void UpdateShift(UserServer.Shift shift)
        {
            base.Channel.UpdateShift(shift);
        }
        
        public System.Threading.Tasks.Task UpdateShiftAsync(UserServer.Shift shift)
        {
            return base.Channel.UpdateShiftAsync(shift);
        }
        
        public bool DeleteShift(UserServer.Shift shift)
        {
            return base.Channel.DeleteShift(shift);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteShiftAsync(UserServer.Shift shift)
        {
            return base.Channel.DeleteShiftAsync(shift);
        }
        
        public UserServer.AssignmentList GetAssignments()
        {
            return base.Channel.GetAssignments();
        }
        
        public System.Threading.Tasks.Task<UserServer.AssignmentList> GetAssignmentsAsync()
        {
            return base.Channel.GetAssignmentsAsync();
        }
        
        public UserServer.Assignment GetAssignmentById(int id)
        {
            return base.Channel.GetAssignmentById(id);
        }
        
        public System.Threading.Tasks.Task<UserServer.Assignment> GetAssignmentByIdAsync(int id)
        {
            return base.Channel.GetAssignmentByIdAsync(id);
        }
        
        public UserServer.Assignment GetAssignmentsBySubject(string Subject)
        {
            return base.Channel.GetAssignmentsBySubject(Subject);
        }
        
        public System.Threading.Tasks.Task<UserServer.Assignment> GetAssignmentsBySubjectAsync(string Subject)
        {
            return base.Channel.GetAssignmentsBySubjectAsync(Subject);
        }
        
        public UserServer.AssignmentList GetAssignmentsByCategory(string Category)
        {
            return base.Channel.GetAssignmentsByCategory(Category);
        }
        
        public System.Threading.Tasks.Task<UserServer.AssignmentList> GetAssignmentsByCategoryAsync(string Category)
        {
            return base.Channel.GetAssignmentsByCategoryAsync(Category);
        }
        
        public UserServer.AssignmentList GetAssignmentByShift(UserServer.Shift shift)
        {
            return base.Channel.GetAssignmentByShift(shift);
        }
        
        public System.Threading.Tasks.Task<UserServer.AssignmentList> GetAssignmentByShiftAsync(UserServer.Shift shift)
        {
            return base.Channel.GetAssignmentByShiftAsync(shift);
        }
        
        public UserServer.Assignment NewAssignment(UserServer.Assignment assignment)
        {
            return base.Channel.NewAssignment(assignment);
        }
        
        public System.Threading.Tasks.Task<UserServer.Assignment> NewAssignmentAsync(UserServer.Assignment assignment)
        {
            return base.Channel.NewAssignmentAsync(assignment);
        }
        
        public void UpdateAssignment(UserServer.Assignment assignment)
        {
            base.Channel.UpdateAssignment(assignment);
        }
        
        public System.Threading.Tasks.Task UpdateAssignmentAsync(UserServer.Assignment assignment)
        {
            return base.Channel.UpdateAssignmentAsync(assignment);
        }
        
        public bool DeleteAssignment(UserServer.Assignment assignment)
        {
            return base.Channel.DeleteAssignment(assignment);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAssignmentAsync(UserServer.Assignment assignment)
        {
            return base.Channel.DeleteAssignmentAsync(assignment);
        }
        
        public UserServer.UserInShiftList GetUsersInShift()
        {
            return base.Channel.GetUsersInShift();
        }
        
        public System.Threading.Tasks.Task<UserServer.UserInShiftList> GetUsersInShiftAsync()
        {
            return base.Channel.GetUsersInShiftAsync();
        }
        
        public UserServer.UserInShift GetByUser(UserServer.User user)
        {
            return base.Channel.GetByUser(user);
        }
        
        public System.Threading.Tasks.Task<UserServer.UserInShift> GetByUserAsync(UserServer.User user)
        {
            return base.Channel.GetByUserAsync(user);
        }
        
        public UserServer.UserInShift NewUserInShift(UserServer.UserInShift user)
        {
            return base.Channel.NewUserInShift(user);
        }
        
        public System.Threading.Tasks.Task<UserServer.UserInShift> NewUserInShiftAsync(UserServer.UserInShift user)
        {
            return base.Channel.NewUserInShiftAsync(user);
        }
        
        public bool UpdateUserInShift(UserServer.UserInShift user)
        {
            return base.Channel.UpdateUserInShift(user);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateUserInShiftAsync(UserServer.UserInShift user)
        {
            return base.Channel.UpdateUserInShiftAsync(user);
        }
        
        public bool DeleteUserInShift(UserServer.UserInShift user)
        {
            return base.Channel.DeleteUserInShift(user);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteUserInShiftAsync(UserServer.UserInShift user)
        {
            return base.Channel.DeleteUserInShiftAsync(user);
        }
        
        public UserServer.CategoryList GetCategories()
        {
            return base.Channel.GetCategories();
        }
        
        public System.Threading.Tasks.Task<UserServer.CategoryList> GetCategoriesAsync()
        {
            return base.Channel.GetCategoriesAsync();
        }
        
        public UserServer.Category GetByName(string name)
        {
            return base.Channel.GetByName(name);
        }
        
        public System.Threading.Tasks.Task<UserServer.Category> GetByNameAsync(string name)
        {
            return base.Channel.GetByNameAsync(name);
        }
        
        public UserServer.Category NewCategory(UserServer.Category category)
        {
            return base.Channel.NewCategory(category);
        }
        
        public System.Threading.Tasks.Task<UserServer.Category> NewCategoryAsync(UserServer.Category category)
        {
            return base.Channel.NewCategoryAsync(category);
        }
        
        public bool UpdateCategory(UserServer.Category category)
        {
            return base.Channel.UpdateCategory(category);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateCategoryAsync(UserServer.Category category)
        {
            return base.Channel.UpdateCategoryAsync(category);
        }
        
        public bool DeleteCategory(UserServer.Category category)
        {
            return base.Channel.DeleteCategory(category);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteCategoryAsync(UserServer.Category category)
        {
            return base.Channel.DeleteCategoryAsync(category);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IUserService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IUserService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WcfService/UserService/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return UserServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IUserService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return UserServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IUserService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IUserService,
        }
    }
}
