//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignmentTable
    {
        public int Id { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public System.DateTime DateOfAssignment { get; set; }
        public Nullable<int> DoneByUser { get; set; }
        public string Summery { get; set; }
        public Nullable<int> ForUser { get; set; }
        public Nullable<int> ForShift { get; set; }
        public int Category { get; set; }
    }
}
