//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInShiftTable
    {
        public int Id { get; set; }
        public int User { get; set; }
        public int Shift { get; set; }
        public bool IsClockedIn { get; set; }
        public System.DateTime UserClockIn { get; set; }
        public bool IsClockedOut { get; set; }
        public Nullable<System.DateTime> UserClockOut { get; set; }
    }
}
